-- Add short-lived OTP challenges for recovery-email registration/change verification.
CREATE TABLE IF NOT EXISTS public.recovery_email_otps (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  email varchar(254) NOT NULL,
  code_hash varchar(64) NOT NULL,
  purpose varchar(40) NOT NULL,
  expires_at timestamptz NOT NULL,
  attempts integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS recovery_email_otps_user_idx
  ON public.recovery_email_otps (user_id, purpose, created_at DESC);

CREATE INDEX IF NOT EXISTS recovery_email_otps_expires_idx
  ON public.recovery_email_otps (expires_at);

ALTER TABLE public.recovery_email_otps ENABLE ROW LEVEL SECURITY;